# Reproduce Electricity with Split at 2014-09-01
python main_depts.py --data electricity --split deepar --seed 1 --lookback 2 --J 4 --output output/electricity/seed:1,lookback:2
python main_depts.py --data electricity --split deepar --seed 1 --lookback 3 --J 4 --output output/electricity/seed:1,lookback:3
python main_depts.py --data electricity --split deepar --seed 1 --lookback 4 --J 4 --output output/electricity/seed:1,lookback:4
python main_depts.py --data electricity --split deepar --seed 1 --lookback 5 --J 4 --output output/electricity/seed:1,lookback:5
python main_depts.py --data electricity --split deepar --seed 1 --lookback 6 --J 4 --output output/electricity/seed:1,lookback:6
python main_depts.py --data electricity --split deepar --seed 1 --lookback 7 --J 4 --output output/electricity/seed:1,lookback:7
python main_depts.py --data electricity --split deepar --seed 2 --lookback 2 --J 4 --output output/electricity/seed:2,lookback:2
python main_depts.py --data electricity --split deepar --seed 2 --lookback 3 --J 4 --output output/electricity/seed:2,lookback:3
python main_depts.py --data electricity --split deepar --seed 2 --lookback 4 --J 4 --output output/electricity/seed:2,lookback:4
python main_depts.py --data electricity --split deepar --seed 2 --lookback 5 --J 4 --output output/electricity/seed:2,lookback:5
python main_depts.py --data electricity --split deepar --seed 2 --lookback 6 --J 4 --output output/electricity/seed:2,lookback:6
python main_depts.py --data electricity --split deepar --seed 2 --lookback 7 --J 4 --output output/electricity/seed:2,lookback:7
python main_depts.py --data electricity --split deepar --seed 3 --lookback 2 --J 4 --output output/electricity/seed:3,lookback:2
python main_depts.py --data electricity --split deepar --seed 3 --lookback 3 --J 4 --output output/electricity/seed:3,lookback:3
python main_depts.py --data electricity --split deepar --seed 3 --lookback 4 --J 4 --output output/electricity/seed:3,lookback:4
python main_depts.py --data electricity --split deepar --seed 3 --lookback 5 --J 4 --output output/electricity/seed:3,lookback:5
python main_depts.py --data electricity --split deepar --seed 3 --lookback 6 --J 4 --output output/electricity/seed:3,lookback:6
python main_depts.py --data electricity --split deepar --seed 3 --lookback 7 --J 4 --output output/electricity/seed:3,lookback:7
python main_depts.py --data electricity --split deepar --seed 4 --lookback 2 --J 4 --output output/electricity/seed:4,lookback:2
python main_depts.py --data electricity --split deepar --seed 4 --lookback 3 --J 4 --output output/electricity/seed:4,lookback:3
python main_depts.py --data electricity --split deepar --seed 4 --lookback 4 --J 4 --output output/electricity/seed:4,lookback:4
python main_depts.py --data electricity --split deepar --seed 4 --lookback 5 --J 4 --output output/electricity/seed:4,lookback:5
python main_depts.py --data electricity --split deepar --seed 4 --lookback 6 --J 4 --output output/electricity/seed:4,lookback:6
python main_depts.py --data electricity --split deepar --seed 4 --lookback 7 --J 4 --output output/electricity/seed:4,lookback:7
python main_depts.py --data electricity --split deepar --seed 5 --lookback 2 --J 4 --output output/electricity/seed:5,lookback:2
python main_depts.py --data electricity --split deepar --seed 5 --lookback 3 --J 4 --output output/electricity/seed:5,lookback:3
python main_depts.py --data electricity --split deepar --seed 5 --lookback 4 --J 4 --output output/electricity/seed:5,lookback:4
python main_depts.py --data electricity --split deepar --seed 5 --lookback 5 --J 4 --output output/electricity/seed:5,lookback:5
python main_depts.py --data electricity --split deepar --seed 5 --lookback 6 --J 4 --output output/electricity/seed:5,lookback:6
python main_depts.py --data electricity --split deepar --seed 5 --lookback 7 --J 4 --output output/electricity/seed:5,lookback:7


# Reproduce Electricity with Split at 2014-12-25
python main_depts.py --data electricity --split last --seed 1 --lookback 2 --J 32 --output output/electricity/seed:1,lookback:2
python main_depts.py --data electricity --split last --seed 1 --lookback 3 --J 32 --output output/electricity/seed:1,lookback:3
python main_depts.py --data electricity --split last --seed 1 --lookback 4 --J 32 --output output/electricity/seed:1,lookback:4
python main_depts.py --data electricity --split last --seed 1 --lookback 5 --J 32 --output output/electricity/seed:1,lookback:5
python main_depts.py --data electricity --split last --seed 1 --lookback 6 --J 32 --output output/electricity/seed:1,lookback:6
python main_depts.py --data electricity --split last --seed 1 --lookback 7 --J 32 --output output/electricity/seed:1,lookback:7
python main_depts.py --data electricity --split last --seed 2 --lookback 2 --J 32 --output output/electricity/seed:2,lookback:2
python main_depts.py --data electricity --split last --seed 2 --lookback 3 --J 32 --output output/electricity/seed:2,lookback:3
python main_depts.py --data electricity --split last --seed 2 --lookback 4 --J 32 --output output/electricity/seed:2,lookback:4
python main_depts.py --data electricity --split last --seed 2 --lookback 5 --J 32 --output output/electricity/seed:2,lookback:5
python main_depts.py --data electricity --split last --seed 2 --lookback 6 --J 32 --output output/electricity/seed:2,lookback:6
python main_depts.py --data electricity --split last --seed 2 --lookback 7 --J 32 --output output/electricity/seed:2,lookback:7
python main_depts.py --data electricity --split last --seed 3 --lookback 2 --J 32 --output output/electricity/seed:3,lookback:2
python main_depts.py --data electricity --split last --seed 3 --lookback 3 --J 32 --output output/electricity/seed:3,lookback:3
python main_depts.py --data electricity --split last --seed 3 --lookback 4 --J 32 --output output/electricity/seed:3,lookback:4
python main_depts.py --data electricity --split last --seed 3 --lookback 5 --J 32 --output output/electricity/seed:3,lookback:5
python main_depts.py --data electricity --split last --seed 3 --lookback 6 --J 32 --output output/electricity/seed:3,lookback:6
python main_depts.py --data electricity --split last --seed 3 --lookback 7 --J 32 --output output/electricity/seed:3,lookback:7
python main_depts.py --data electricity --split last --seed 4 --lookback 2 --J 32 --output output/electricity/seed:4,lookback:2
python main_depts.py --data electricity --split last --seed 4 --lookback 3 --J 32 --output output/electricity/seed:4,lookback:3
python main_depts.py --data electricity --split last --seed 4 --lookback 4 --J 32 --output output/electricity/seed:4,lookback:4
python main_depts.py --data electricity --split last --seed 4 --lookback 5 --J 32 --output output/electricity/seed:4,lookback:5
python main_depts.py --data electricity --split last --seed 4 --lookback 6 --J 32 --output output/electricity/seed:4,lookback:6
python main_depts.py --data electricity --split last --seed 4 --lookback 7 --J 32 --output output/electricity/seed:4,lookback:7
python main_depts.py --data electricity --split last --seed 5 --lookback 2 --J 32 --output output/electricity/seed:5,lookback:2
python main_depts.py --data electricity --split last --seed 5 --lookback 3 --J 32 --output output/electricity/seed:5,lookback:3
python main_depts.py --data electricity --split last --seed 5 --lookback 4 --J 32 --output output/electricity/seed:5,lookback:4
python main_depts.py --data electricity --split last --seed 5 --lookback 5 --J 32 --output output/electricity/seed:5,lookback:5
python main_depts.py --data electricity --split last --seed 5 --lookback 6 --J 32 --output output/electricity/seed:5,lookback:6
python main_depts.py --data electricity --split last --seed 5 --lookback 7 --J 32 --output output/electricity/seed:5,lookback:7


# Reproduce Traffic with Split at 2008-06-15
python main_depts.py --data traffic --split deepar --seed 1 --lookback 2 --J 8 --output output/traffic/seed:1,lookback:2
python main_depts.py --data traffic --split deepar --seed 1 --lookback 3 --J 8 --output output/traffic/seed:1,lookback:3
python main_depts.py --data traffic --split deepar --seed 1 --lookback 4 --J 8 --output output/traffic/seed:1,lookback:4
python main_depts.py --data traffic --split deepar --seed 1 --lookback 5 --J 8 --output output/traffic/seed:1,lookback:5
python main_depts.py --data traffic --split deepar --seed 1 --lookback 6 --J 8 --output output/traffic/seed:1,lookback:6
python main_depts.py --data traffic --split deepar --seed 1 --lookback 7 --J 8 --output output/traffic/seed:1,lookback:7
python main_depts.py --data traffic --split deepar --seed 2 --lookback 2 --J 8 --output output/traffic/seed:2,lookback:2
python main_depts.py --data traffic --split deepar --seed 2 --lookback 3 --J 8 --output output/traffic/seed:2,lookback:3
python main_depts.py --data traffic --split deepar --seed 2 --lookback 4 --J 8 --output output/traffic/seed:2,lookback:4
python main_depts.py --data traffic --split deepar --seed 2 --lookback 5 --J 8 --output output/traffic/seed:2,lookback:5
python main_depts.py --data traffic --split deepar --seed 2 --lookback 6 --J 8 --output output/traffic/seed:2,lookback:6
python main_depts.py --data traffic --split deepar --seed 2 --lookback 7 --J 8 --output output/traffic/seed:2,lookback:7
python main_depts.py --data traffic --split deepar --seed 3 --lookback 2 --J 8 --output output/traffic/seed:3,lookback:2
python main_depts.py --data traffic --split deepar --seed 3 --lookback 3 --J 8 --output output/traffic/seed:3,lookback:3
python main_depts.py --data traffic --split deepar --seed 3 --lookback 4 --J 8 --output output/traffic/seed:3,lookback:4
python main_depts.py --data traffic --split deepar --seed 3 --lookback 5 --J 8 --output output/traffic/seed:3,lookback:5
python main_depts.py --data traffic --split deepar --seed 3 --lookback 6 --J 8 --output output/traffic/seed:3,lookback:6
python main_depts.py --data traffic --split deepar --seed 3 --lookback 7 --J 8 --output output/traffic/seed:3,lookback:7
python main_depts.py --data traffic --split deepar --seed 4 --lookback 2 --J 8 --output output/traffic/seed:4,lookback:2
python main_depts.py --data traffic --split deepar --seed 4 --lookback 3 --J 8 --output output/traffic/seed:4,lookback:3
python main_depts.py --data traffic --split deepar --seed 4 --lookback 4 --J 8 --output output/traffic/seed:4,lookback:4
python main_depts.py --data traffic --split deepar --seed 4 --lookback 5 --J 8 --output output/traffic/seed:4,lookback:5
python main_depts.py --data traffic --split deepar --seed 4 --lookback 6 --J 8 --output output/traffic/seed:4,lookback:6
python main_depts.py --data traffic --split deepar --seed 4 --lookback 7 --J 8 --output output/traffic/seed:4,lookback:7
python main_depts.py --data traffic --split deepar --seed 5 --lookback 2 --J 8 --output output/traffic/seed:5,lookback:2
python main_depts.py --data traffic --split deepar --seed 5 --lookback 3 --J 8 --output output/traffic/seed:5,lookback:3
python main_depts.py --data traffic --split deepar --seed 5 --lookback 4 --J 8 --output output/traffic/seed:5,lookback:4
python main_depts.py --data traffic --split deepar --seed 5 --lookback 5 --J 8 --output output/traffic/seed:5,lookback:5
python main_depts.py --data traffic --split deepar --seed 5 --lookback 6 --J 8 --output output/traffic/seed:5,lookback:6
python main_depts.py --data traffic --split deepar --seed 5 --lookback 7 --J 8 --output output/traffic/seed:5,lookback:7


# Reproduce Traffic with Split at 2009-03-24
python main_depts.py --data traffic --split last --seed 1 --lookback 2 --J 8 --output output/traffic/seed:1,lookback:2
python main_depts.py --data traffic --split last --seed 1 --lookback 3 --J 8 --output output/traffic/seed:1,lookback:3
python main_depts.py --data traffic --split last --seed 1 --lookback 4 --J 8 --output output/traffic/seed:1,lookback:4
python main_depts.py --data traffic --split last --seed 1 --lookback 5 --J 8 --output output/traffic/seed:1,lookback:5
python main_depts.py --data traffic --split last --seed 1 --lookback 6 --J 8 --output output/traffic/seed:1,lookback:6
python main_depts.py --data traffic --split last --seed 1 --lookback 7 --J 8 --output output/traffic/seed:1,lookback:7
python main_depts.py --data traffic --split last --seed 2 --lookback 2 --J 8 --output output/traffic/seed:2,lookback:2
python main_depts.py --data traffic --split last --seed 2 --lookback 3 --J 8 --output output/traffic/seed:2,lookback:3
python main_depts.py --data traffic --split last --seed 2 --lookback 4 --J 8 --output output/traffic/seed:2,lookback:4
python main_depts.py --data traffic --split last --seed 2 --lookback 5 --J 8 --output output/traffic/seed:2,lookback:5
python main_depts.py --data traffic --split last --seed 2 --lookback 6 --J 8 --output output/traffic/seed:2,lookback:6
python main_depts.py --data traffic --split last --seed 2 --lookback 7 --J 8 --output output/traffic/seed:2,lookback:7
python main_depts.py --data traffic --split last --seed 3 --lookback 2 --J 8 --output output/traffic/seed:3,lookback:2
python main_depts.py --data traffic --split last --seed 3 --lookback 3 --J 8 --output output/traffic/seed:3,lookback:3
python main_depts.py --data traffic --split last --seed 3 --lookback 4 --J 8 --output output/traffic/seed:3,lookback:4
python main_depts.py --data traffic --split last --seed 3 --lookback 5 --J 8 --output output/traffic/seed:3,lookback:5
python main_depts.py --data traffic --split last --seed 3 --lookback 6 --J 8 --output output/traffic/seed:3,lookback:6
python main_depts.py --data traffic --split last --seed 3 --lookback 7 --J 8 --output output/traffic/seed:3,lookback:7
python main_depts.py --data traffic --split last --seed 4 --lookback 2 --J 8 --output output/traffic/seed:4,lookback:2
python main_depts.py --data traffic --split last --seed 4 --lookback 3 --J 8 --output output/traffic/seed:4,lookback:3
python main_depts.py --data traffic --split last --seed 4 --lookback 4 --J 8 --output output/traffic/seed:4,lookback:4
python main_depts.py --data traffic --split last --seed 4 --lookback 5 --J 8 --output output/traffic/seed:4,lookback:5
python main_depts.py --data traffic --split last --seed 4 --lookback 6 --J 8 --output output/traffic/seed:4,lookback:6
python main_depts.py --data traffic --split last --seed 4 --lookback 7 --J 8 --output output/traffic/seed:4,lookback:7
python main_depts.py --data traffic --split last --seed 5 --lookback 2 --J 8 --output output/traffic/seed:5,lookback:2
python main_depts.py --data traffic --split last --seed 5 --lookback 3 --J 8 --output output/traffic/seed:5,lookback:3
python main_depts.py --data traffic --split last --seed 5 --lookback 4 --J 8 --output output/traffic/seed:5,lookback:4
python main_depts.py --data traffic --split last --seed 5 --lookback 5 --J 8 --output output/traffic/seed:5,lookback:5
python main_depts.py --data traffic --split last --seed 5 --lookback 6 --J 8 --output output/traffic/seed:5,lookback:6
python main_depts.py --data traffic --split last --seed 5 --lookback 7 --J 8 --output output/traffic/seed:5,lookback:7


# Reproduce Caiso with Split at 2020-01-01
python main_depts.py --data caiso --split last18months --seed 1 --lookback 2 --J 8 --output output/caiso/seed:1,lookback:2
python main_depts.py --data caiso --split last18months --seed 1 --lookback 3 --J 8 --output output/caiso/seed:1,lookback:3
python main_depts.py --data caiso --split last18months --seed 1 --lookback 4 --J 8 --output output/caiso/seed:1,lookback:4
python main_depts.py --data caiso --split last18months --seed 1 --lookback 5 --J 8 --output output/caiso/seed:1,lookback:5
python main_depts.py --data caiso --split last18months --seed 1 --lookback 6 --J 8 --output output/caiso/seed:1,lookback:6
python main_depts.py --data caiso --split last18months --seed 1 --lookback 7 --J 8 --output output/caiso/seed:1,lookback:7
python main_depts.py --data caiso --split last18months --seed 2 --lookback 2 --J 8 --output output/caiso/seed:2,lookback:2
python main_depts.py --data caiso --split last18months --seed 2 --lookback 3 --J 8 --output output/caiso/seed:2,lookback:3
python main_depts.py --data caiso --split last18months --seed 2 --lookback 4 --J 8 --output output/caiso/seed:2,lookback:4
python main_depts.py --data caiso --split last18months --seed 2 --lookback 5 --J 8 --output output/caiso/seed:2,lookback:5
python main_depts.py --data caiso --split last18months --seed 2 --lookback 6 --J 8 --output output/caiso/seed:2,lookback:6
python main_depts.py --data caiso --split last18months --seed 2 --lookback 7 --J 8 --output output/caiso/seed:2,lookback:7
python main_depts.py --data caiso --split last18months --seed 3 --lookback 2 --J 8 --output output/caiso/seed:3,lookback:2
python main_depts.py --data caiso --split last18months --seed 3 --lookback 3 --J 8 --output output/caiso/seed:3,lookback:3
python main_depts.py --data caiso --split last18months --seed 3 --lookback 4 --J 8 --output output/caiso/seed:3,lookback:4
python main_depts.py --data caiso --split last18months --seed 3 --lookback 5 --J 8 --output output/caiso/seed:3,lookback:5
python main_depts.py --data caiso --split last18months --seed 3 --lookback 6 --J 8 --output output/caiso/seed:3,lookback:6
python main_depts.py --data caiso --split last18months --seed 3 --lookback 7 --J 8 --output output/caiso/seed:3,lookback:7
python main_depts.py --data caiso --split last18months --seed 4 --lookback 2 --J 8 --output output/caiso/seed:4,lookback:2
python main_depts.py --data caiso --split last18months --seed 4 --lookback 3 --J 8 --output output/caiso/seed:4,lookback:3
python main_depts.py --data caiso --split last18months --seed 4 --lookback 4 --J 8 --output output/caiso/seed:4,lookback:4
python main_depts.py --data caiso --split last18months --seed 4 --lookback 5 --J 8 --output output/caiso/seed:4,lookback:5
python main_depts.py --data caiso --split last18months --seed 4 --lookback 6 --J 8 --output output/caiso/seed:4,lookback:6
python main_depts.py --data caiso --split last18months --seed 4 --lookback 7 --J 8 --output output/caiso/seed:4,lookback:7
python main_depts.py --data caiso --split last18months --seed 5 --lookback 2 --J 8 --output output/caiso/seed:5,lookback:2
python main_depts.py --data caiso --split last18months --seed 5 --lookback 3 --J 8 --output output/caiso/seed:5,lookback:3
python main_depts.py --data caiso --split last18months --seed 5 --lookback 4 --J 8 --output output/caiso/seed:5,lookback:4
python main_depts.py --data caiso --split last18months --seed 5 --lookback 5 --J 8 --output output/caiso/seed:5,lookback:5
python main_depts.py --data caiso --split last18months --seed 5 --lookback 6 --J 8 --output output/caiso/seed:5,lookback:6
python main_depts.py --data caiso --split last18months --seed 5 --lookback 7 --J 8 --output output/caiso/seed:5,lookback:7


# Reproduce Caiso with Split at 2020-04-01
python main_depts.py --data caiso --split last15months --seed 1 --lookback 2 --J 32 --output output/caiso/seed:1,lookback:2
python main_depts.py --data caiso --split last15months --seed 1 --lookback 3 --J 32 --output output/caiso/seed:1,lookback:3
python main_depts.py --data caiso --split last15months --seed 1 --lookback 4 --J 32 --output output/caiso/seed:1,lookback:4
python main_depts.py --data caiso --split last15months --seed 1 --lookback 5 --J 32 --output output/caiso/seed:1,lookback:5
python main_depts.py --data caiso --split last15months --seed 1 --lookback 6 --J 32 --output output/caiso/seed:1,lookback:6
python main_depts.py --data caiso --split last15months --seed 1 --lookback 7 --J 32 --output output/caiso/seed:1,lookback:7
python main_depts.py --data caiso --split last15months --seed 2 --lookback 2 --J 32 --output output/caiso/seed:2,lookback:2
python main_depts.py --data caiso --split last15months --seed 2 --lookback 3 --J 32 --output output/caiso/seed:2,lookback:3
python main_depts.py --data caiso --split last15months --seed 2 --lookback 4 --J 32 --output output/caiso/seed:2,lookback:4
python main_depts.py --data caiso --split last15months --seed 2 --lookback 5 --J 32 --output output/caiso/seed:2,lookback:5
python main_depts.py --data caiso --split last15months --seed 2 --lookback 6 --J 32 --output output/caiso/seed:2,lookback:6
python main_depts.py --data caiso --split last15months --seed 2 --lookback 7 --J 32 --output output/caiso/seed:2,lookback:7
python main_depts.py --data caiso --split last15months --seed 3 --lookback 2 --J 32 --output output/caiso/seed:3,lookback:2
python main_depts.py --data caiso --split last15months --seed 3 --lookback 3 --J 32 --output output/caiso/seed:3,lookback:3
python main_depts.py --data caiso --split last15months --seed 3 --lookback 4 --J 32 --output output/caiso/seed:3,lookback:4
python main_depts.py --data caiso --split last15months --seed 3 --lookback 5 --J 32 --output output/caiso/seed:3,lookback:5
python main_depts.py --data caiso --split last15months --seed 3 --lookback 6 --J 32 --output output/caiso/seed:3,lookback:6
python main_depts.py --data caiso --split last15months --seed 3 --lookback 7 --J 32 --output output/caiso/seed:3,lookback:7
python main_depts.py --data caiso --split last15months --seed 4 --lookback 2 --J 32 --output output/caiso/seed:4,lookback:2
python main_depts.py --data caiso --split last15months --seed 4 --lookback 3 --J 32 --output output/caiso/seed:4,lookback:3
python main_depts.py --data caiso --split last15months --seed 4 --lookback 4 --J 32 --output output/caiso/seed:4,lookback:4
python main_depts.py --data caiso --split last15months --seed 4 --lookback 5 --J 32 --output output/caiso/seed:4,lookback:5
python main_depts.py --data caiso --split last15months --seed 4 --lookback 6 --J 32 --output output/caiso/seed:4,lookback:6
python main_depts.py --data caiso --split last15months --seed 4 --lookback 7 --J 32 --output output/caiso/seed:4,lookback:7
python main_depts.py --data caiso --split last15months --seed 5 --lookback 2 --J 32 --output output/caiso/seed:5,lookback:2
python main_depts.py --data caiso --split last15months --seed 5 --lookback 3 --J 32 --output output/caiso/seed:5,lookback:3
python main_depts.py --data caiso --split last15months --seed 5 --lookback 4 --J 32 --output output/caiso/seed:5,lookback:4
python main_depts.py --data caiso --split last15months --seed 5 --lookback 5 --J 32 --output output/caiso/seed:5,lookback:5
python main_depts.py --data caiso --split last15months --seed 5 --lookback 6 --J 32 --output output/caiso/seed:5,lookback:6
python main_depts.py --data caiso --split last15months --seed 5 --lookback 7 --J 32 --output output/caiso/seed:5,lookback:7


# Reproduce Caiso with Split at 2020-07-01
python main_depts.py --data caiso --split last12months --seed 1 --lookback 2 --J 32 --output output/caiso/seed:1,lookback:2
python main_depts.py --data caiso --split last12months --seed 1 --lookback 3 --J 32 --output output/caiso/seed:1,lookback:3
python main_depts.py --data caiso --split last12months --seed 1 --lookback 4 --J 32 --output output/caiso/seed:1,lookback:4
python main_depts.py --data caiso --split last12months --seed 1 --lookback 5 --J 32 --output output/caiso/seed:1,lookback:5
python main_depts.py --data caiso --split last12months --seed 1 --lookback 6 --J 32 --output output/caiso/seed:1,lookback:6
python main_depts.py --data caiso --split last12months --seed 1 --lookback 7 --J 32 --output output/caiso/seed:1,lookback:7
python main_depts.py --data caiso --split last12months --seed 2 --lookback 2 --J 32 --output output/caiso/seed:2,lookback:2
python main_depts.py --data caiso --split last12months --seed 2 --lookback 3 --J 32 --output output/caiso/seed:2,lookback:3
python main_depts.py --data caiso --split last12months --seed 2 --lookback 4 --J 32 --output output/caiso/seed:2,lookback:4
python main_depts.py --data caiso --split last12months --seed 2 --lookback 5 --J 32 --output output/caiso/seed:2,lookback:5
python main_depts.py --data caiso --split last12months --seed 2 --lookback 6 --J 32 --output output/caiso/seed:2,lookback:6
python main_depts.py --data caiso --split last12months --seed 2 --lookback 7 --J 32 --output output/caiso/seed:2,lookback:7
python main_depts.py --data caiso --split last12months --seed 3 --lookback 2 --J 32 --output output/caiso/seed:3,lookback:2
python main_depts.py --data caiso --split last12months --seed 3 --lookback 3 --J 32 --output output/caiso/seed:3,lookback:3
python main_depts.py --data caiso --split last12months --seed 3 --lookback 4 --J 32 --output output/caiso/seed:3,lookback:4
python main_depts.py --data caiso --split last12months --seed 3 --lookback 5 --J 32 --output output/caiso/seed:3,lookback:5
python main_depts.py --data caiso --split last12months --seed 3 --lookback 6 --J 32 --output output/caiso/seed:3,lookback:6
python main_depts.py --data caiso --split last12months --seed 3 --lookback 7 --J 32 --output output/caiso/seed:3,lookback:7
python main_depts.py --data caiso --split last12months --seed 4 --lookback 2 --J 32 --output output/caiso/seed:4,lookback:2
python main_depts.py --data caiso --split last12months --seed 4 --lookback 3 --J 32 --output output/caiso/seed:4,lookback:3
python main_depts.py --data caiso --split last12months --seed 4 --lookback 4 --J 32 --output output/caiso/seed:4,lookback:4
python main_depts.py --data caiso --split last12months --seed 4 --lookback 5 --J 32 --output output/caiso/seed:4,lookback:5
python main_depts.py --data caiso --split last12months --seed 4 --lookback 6 --J 32 --output output/caiso/seed:4,lookback:6
python main_depts.py --data caiso --split last12months --seed 4 --lookback 7 --J 32 --output output/caiso/seed:4,lookback:7
python main_depts.py --data caiso --split last12months --seed 5 --lookback 2 --J 32 --output output/caiso/seed:5,lookback:2
python main_depts.py --data caiso --split last12months --seed 5 --lookback 3 --J 32 --output output/caiso/seed:5,lookback:3
python main_depts.py --data caiso --split last12months --seed 5 --lookback 4 --J 32 --output output/caiso/seed:5,lookback:4
python main_depts.py --data caiso --split last12months --seed 5 --lookback 5 --J 32 --output output/caiso/seed:5,lookback:5
python main_depts.py --data caiso --split last12months --seed 5 --lookback 6 --J 32 --output output/caiso/seed:5,lookback:6
python main_depts.py --data caiso --split last12months --seed 5 --lookback 7 --J 32 --output output/caiso/seed:5,lookback:7


# Reproduce Caiso with Split at 2020-10-01
python main_depts.py --data caiso --split last9months --seed 1 --lookback 2 --J 8 --output output/caiso/seed:1,lookback:2
python main_depts.py --data caiso --split last9months --seed 1 --lookback 3 --J 8 --output output/caiso/seed:1,lookback:3
python main_depts.py --data caiso --split last9months --seed 1 --lookback 4 --J 8 --output output/caiso/seed:1,lookback:4
python main_depts.py --data caiso --split last9months --seed 1 --lookback 5 --J 8 --output output/caiso/seed:1,lookback:5
python main_depts.py --data caiso --split last9months --seed 1 --lookback 6 --J 8 --output output/caiso/seed:1,lookback:6
python main_depts.py --data caiso --split last9months --seed 1 --lookback 7 --J 8 --output output/caiso/seed:1,lookback:7
python main_depts.py --data caiso --split last9months --seed 2 --lookback 2 --J 8 --output output/caiso/seed:2,lookback:2
python main_depts.py --data caiso --split last9months --seed 2 --lookback 3 --J 8 --output output/caiso/seed:2,lookback:3
python main_depts.py --data caiso --split last9months --seed 2 --lookback 4 --J 8 --output output/caiso/seed:2,lookback:4
python main_depts.py --data caiso --split last9months --seed 2 --lookback 5 --J 8 --output output/caiso/seed:2,lookback:5
python main_depts.py --data caiso --split last9months --seed 2 --lookback 6 --J 8 --output output/caiso/seed:2,lookback:6
python main_depts.py --data caiso --split last9months --seed 2 --lookback 7 --J 8 --output output/caiso/seed:2,lookback:7
python main_depts.py --data caiso --split last9months --seed 3 --lookback 2 --J 8 --output output/caiso/seed:3,lookback:2
python main_depts.py --data caiso --split last9months --seed 3 --lookback 3 --J 8 --output output/caiso/seed:3,lookback:3
python main_depts.py --data caiso --split last9months --seed 3 --lookback 4 --J 8 --output output/caiso/seed:3,lookback:4
python main_depts.py --data caiso --split last9months --seed 3 --lookback 5 --J 8 --output output/caiso/seed:3,lookback:5
python main_depts.py --data caiso --split last9months --seed 3 --lookback 6 --J 8 --output output/caiso/seed:3,lookback:6
python main_depts.py --data caiso --split last9months --seed 3 --lookback 7 --J 8 --output output/caiso/seed:3,lookback:7
python main_depts.py --data caiso --split last9months --seed 4 --lookback 2 --J 8 --output output/caiso/seed:4,lookback:2
python main_depts.py --data caiso --split last9months --seed 4 --lookback 3 --J 8 --output output/caiso/seed:4,lookback:3
python main_depts.py --data caiso --split last9months --seed 4 --lookback 4 --J 8 --output output/caiso/seed:4,lookback:4
python main_depts.py --data caiso --split last9months --seed 4 --lookback 5 --J 8 --output output/caiso/seed:4,lookback:5
python main_depts.py --data caiso --split last9months --seed 4 --lookback 6 --J 8 --output output/caiso/seed:4,lookback:6
python main_depts.py --data caiso --split last9months --seed 4 --lookback 7 --J 8 --output output/caiso/seed:4,lookback:7
python main_depts.py --data caiso --split last9months --seed 5 --lookback 2 --J 8 --output output/caiso/seed:5,lookback:2
python main_depts.py --data caiso --split last9months --seed 5 --lookback 3 --J 8 --output output/caiso/seed:5,lookback:3
python main_depts.py --data caiso --split last9months --seed 5 --lookback 4 --J 8 --output output/caiso/seed:5,lookback:4
python main_depts.py --data caiso --split last9months --seed 5 --lookback 5 --J 8 --output output/caiso/seed:5,lookback:5
python main_depts.py --data caiso --split last9months --seed 5 --lookback 6 --J 8 --output output/caiso/seed:5,lookback:6
python main_depts.py --data caiso --split last9months --seed 5 --lookback 7 --J 8 --output output/caiso/seed:5,lookback:7


# Reproduce NP with Split at 2020-01-01
python main_depts.py --data product --split last12months --seed 1 --lookback 2 --J 8 --output output/product/seed:1,lookback:2
python main_depts.py --data product --split last12months --seed 1 --lookback 3 --J 8 --output output/product/seed:1,lookback:3
python main_depts.py --data product --split last12months --seed 1 --lookback 4 --J 8 --output output/product/seed:1,lookback:4
python main_depts.py --data product --split last12months --seed 1 --lookback 5 --J 8 --output output/product/seed:1,lookback:5
python main_depts.py --data product --split last12months --seed 1 --lookback 6 --J 8 --output output/product/seed:1,lookback:6
python main_depts.py --data product --split last12months --seed 1 --lookback 7 --J 8 --output output/product/seed:1,lookback:7
python main_depts.py --data product --split last12months --seed 2 --lookback 2 --J 8 --output output/product/seed:2,lookback:2
python main_depts.py --data product --split last12months --seed 2 --lookback 3 --J 8 --output output/product/seed:2,lookback:3
python main_depts.py --data product --split last12months --seed 2 --lookback 4 --J 8 --output output/product/seed:2,lookback:4
python main_depts.py --data product --split last12months --seed 2 --lookback 5 --J 8 --output output/product/seed:2,lookback:5
python main_depts.py --data product --split last12months --seed 2 --lookback 6 --J 8 --output output/product/seed:2,lookback:6
python main_depts.py --data product --split last12months --seed 2 --lookback 7 --J 8 --output output/product/seed:2,lookback:7
python main_depts.py --data product --split last12months --seed 3 --lookback 2 --J 8 --output output/product/seed:3,lookback:2
python main_depts.py --data product --split last12months --seed 3 --lookback 3 --J 8 --output output/product/seed:3,lookback:3
python main_depts.py --data product --split last12months --seed 3 --lookback 4 --J 8 --output output/product/seed:3,lookback:4
python main_depts.py --data product --split last12months --seed 3 --lookback 5 --J 8 --output output/product/seed:3,lookback:5
python main_depts.py --data product --split last12months --seed 3 --lookback 6 --J 8 --output output/product/seed:3,lookback:6
python main_depts.py --data product --split last12months --seed 3 --lookback 7 --J 8 --output output/product/seed:3,lookback:7
python main_depts.py --data product --split last12months --seed 4 --lookback 2 --J 8 --output output/product/seed:4,lookback:2
python main_depts.py --data product --split last12months --seed 4 --lookback 3 --J 8 --output output/product/seed:4,lookback:3
python main_depts.py --data product --split last12months --seed 4 --lookback 4 --J 8 --output output/product/seed:4,lookback:4
python main_depts.py --data product --split last12months --seed 4 --lookback 5 --J 8 --output output/product/seed:4,lookback:5
python main_depts.py --data product --split last12months --seed 4 --lookback 6 --J 8 --output output/product/seed:4,lookback:6
python main_depts.py --data product --split last12months --seed 4 --lookback 7 --J 8 --output output/product/seed:4,lookback:7
python main_depts.py --data product --split last12months --seed 5 --lookback 2 --J 8 --output output/product/seed:5,lookback:2
python main_depts.py --data product --split last12months --seed 5 --lookback 3 --J 8 --output output/product/seed:5,lookback:3
python main_depts.py --data product --split last12months --seed 5 --lookback 4 --J 8 --output output/product/seed:5,lookback:4
python main_depts.py --data product --split last12months --seed 5 --lookback 5 --J 8 --output output/product/seed:5,lookback:5
python main_depts.py --data product --split last12months --seed 5 --lookback 6 --J 8 --output output/product/seed:5,lookback:6
python main_depts.py --data product --split last12months --seed 5 --lookback 7 --J 8 --output output/product/seed:5,lookback:7


# Reproduce NP with Split at 2020-04-01
python main_depts.py --data product --split last9months --seed 1 --lookback 2 --J 8 --output output/product/seed:1,lookback:2
python main_depts.py --data product --split last9months --seed 1 --lookback 3 --J 8 --output output/product/seed:1,lookback:3
python main_depts.py --data product --split last9months --seed 1 --lookback 4 --J 8 --output output/product/seed:1,lookback:4
python main_depts.py --data product --split last9months --seed 1 --lookback 5 --J 8 --output output/product/seed:1,lookback:5
python main_depts.py --data product --split last9months --seed 1 --lookback 6 --J 8 --output output/product/seed:1,lookback:6
python main_depts.py --data product --split last9months --seed 1 --lookback 7 --J 8 --output output/product/seed:1,lookback:7
python main_depts.py --data product --split last9months --seed 2 --lookback 2 --J 8 --output output/product/seed:2,lookback:2
python main_depts.py --data product --split last9months --seed 2 --lookback 3 --J 8 --output output/product/seed:2,lookback:3
python main_depts.py --data product --split last9months --seed 2 --lookback 4 --J 8 --output output/product/seed:2,lookback:4
python main_depts.py --data product --split last9months --seed 2 --lookback 5 --J 8 --output output/product/seed:2,lookback:5
python main_depts.py --data product --split last9months --seed 2 --lookback 6 --J 8 --output output/product/seed:2,lookback:6
python main_depts.py --data product --split last9months --seed 2 --lookback 7 --J 8 --output output/product/seed:2,lookback:7
python main_depts.py --data product --split last9months --seed 3 --lookback 2 --J 8 --output output/product/seed:3,lookback:2
python main_depts.py --data product --split last9months --seed 3 --lookback 3 --J 8 --output output/product/seed:3,lookback:3
python main_depts.py --data product --split last9months --seed 3 --lookback 4 --J 8 --output output/product/seed:3,lookback:4
python main_depts.py --data product --split last9months --seed 3 --lookback 5 --J 8 --output output/product/seed:3,lookback:5
python main_depts.py --data product --split last9months --seed 3 --lookback 6 --J 8 --output output/product/seed:3,lookback:6
python main_depts.py --data product --split last9months --seed 3 --lookback 7 --J 8 --output output/product/seed:3,lookback:7
python main_depts.py --data product --split last9months --seed 4 --lookback 2 --J 8 --output output/product/seed:4,lookback:2
python main_depts.py --data product --split last9months --seed 4 --lookback 3 --J 8 --output output/product/seed:4,lookback:3
python main_depts.py --data product --split last9months --seed 4 --lookback 4 --J 8 --output output/product/seed:4,lookback:4
python main_depts.py --data product --split last9months --seed 4 --lookback 5 --J 8 --output output/product/seed:4,lookback:5
python main_depts.py --data product --split last9months --seed 4 --lookback 6 --J 8 --output output/product/seed:4,lookback:6
python main_depts.py --data product --split last9months --seed 4 --lookback 7 --J 8 --output output/product/seed:4,lookback:7
python main_depts.py --data product --split last9months --seed 5 --lookback 2 --J 8 --output output/product/seed:5,lookback:2
python main_depts.py --data product --split last9months --seed 5 --lookback 3 --J 8 --output output/product/seed:5,lookback:3
python main_depts.py --data product --split last9months --seed 5 --lookback 4 --J 8 --output output/product/seed:5,lookback:4
python main_depts.py --data product --split last9months --seed 5 --lookback 5 --J 8 --output output/product/seed:5,lookback:5
python main_depts.py --data product --split last9months --seed 5 --lookback 6 --J 8 --output output/product/seed:5,lookback:6
python main_depts.py --data product --split last9months --seed 5 --lookback 7 --J 8 --output output/product/seed:5,lookback:7


# Reproduce NP with Split at 2020-07-01
python main_depts.py --data product --split last6months --seed 1 --lookback 2 --J 32 --output output/product/seed:1,lookback:2
python main_depts.py --data product --split last6months --seed 1 --lookback 3 --J 32 --output output/product/seed:1,lookback:3
python main_depts.py --data product --split last6months --seed 1 --lookback 4 --J 32 --output output/product/seed:1,lookback:4
python main_depts.py --data product --split last6months --seed 1 --lookback 5 --J 32 --output output/product/seed:1,lookback:5
python main_depts.py --data product --split last6months --seed 1 --lookback 6 --J 32 --output output/product/seed:1,lookback:6
python main_depts.py --data product --split last6months --seed 1 --lookback 7 --J 32 --output output/product/seed:1,lookback:7
python main_depts.py --data product --split last6months --seed 2 --lookback 2 --J 32 --output output/product/seed:2,lookback:2
python main_depts.py --data product --split last6months --seed 2 --lookback 3 --J 32 --output output/product/seed:2,lookback:3
python main_depts.py --data product --split last6months --seed 2 --lookback 4 --J 32 --output output/product/seed:2,lookback:4
python main_depts.py --data product --split last6months --seed 2 --lookback 5 --J 32 --output output/product/seed:2,lookback:5
python main_depts.py --data product --split last6months --seed 2 --lookback 6 --J 32 --output output/product/seed:2,lookback:6
python main_depts.py --data product --split last6months --seed 2 --lookback 7 --J 32 --output output/product/seed:2,lookback:7
python main_depts.py --data product --split last6months --seed 3 --lookback 2 --J 32 --output output/product/seed:3,lookback:2
python main_depts.py --data product --split last6months --seed 3 --lookback 3 --J 32 --output output/product/seed:3,lookback:3
python main_depts.py --data product --split last6months --seed 3 --lookback 4 --J 32 --output output/product/seed:3,lookback:4
python main_depts.py --data product --split last6months --seed 3 --lookback 5 --J 32 --output output/product/seed:3,lookback:5
python main_depts.py --data product --split last6months --seed 3 --lookback 6 --J 32 --output output/product/seed:3,lookback:6
python main_depts.py --data product --split last6months --seed 3 --lookback 7 --J 32 --output output/product/seed:3,lookback:7
python main_depts.py --data product --split last6months --seed 4 --lookback 2 --J 32 --output output/product/seed:4,lookback:2
python main_depts.py --data product --split last6months --seed 4 --lookback 3 --J 32 --output output/product/seed:4,lookback:3
python main_depts.py --data product --split last6months --seed 4 --lookback 4 --J 32 --output output/product/seed:4,lookback:4
python main_depts.py --data product --split last6months --seed 4 --lookback 5 --J 32 --output output/product/seed:4,lookback:5
python main_depts.py --data product --split last6months --seed 4 --lookback 6 --J 32 --output output/product/seed:4,lookback:6
python main_depts.py --data product --split last6months --seed 4 --lookback 7 --J 32 --output output/product/seed:4,lookback:7
python main_depts.py --data product --split last6months --seed 5 --lookback 2 --J 32 --output output/product/seed:5,lookback:2
python main_depts.py --data product --split last6months --seed 5 --lookback 3 --J 32 --output output/product/seed:5,lookback:3
python main_depts.py --data product --split last6months --seed 5 --lookback 4 --J 32 --output output/product/seed:5,lookback:4
python main_depts.py --data product --split last6months --seed 5 --lookback 5 --J 32 --output output/product/seed:5,lookback:5
python main_depts.py --data product --split last6months --seed 5 --lookback 6 --J 32 --output output/product/seed:5,lookback:6
python main_depts.py --data product --split last6months --seed 5 --lookback 7 --J 32 --output output/product/seed:5,lookback:7


# Reproduce NP with Split at 2020-10-01
python main_depts.py --data product --split last3months --seed 1 --lookback 2 --J 32 --output output/product/seed:1,lookback:2
python main_depts.py --data product --split last3months --seed 1 --lookback 3 --J 32 --output output/product/seed:1,lookback:3
python main_depts.py --data product --split last3months --seed 1 --lookback 4 --J 32 --output output/product/seed:1,lookback:4
python main_depts.py --data product --split last3months --seed 1 --lookback 5 --J 32 --output output/product/seed:1,lookback:5
python main_depts.py --data product --split last3months --seed 1 --lookback 6 --J 32 --output output/product/seed:1,lookback:6
python main_depts.py --data product --split last3months --seed 1 --lookback 7 --J 32 --output output/product/seed:1,lookback:7
python main_depts.py --data product --split last3months --seed 2 --lookback 2 --J 32 --output output/product/seed:2,lookback:2
python main_depts.py --data product --split last3months --seed 2 --lookback 3 --J 32 --output output/product/seed:2,lookback:3
python main_depts.py --data product --split last3months --seed 2 --lookback 4 --J 32 --output output/product/seed:2,lookback:4
python main_depts.py --data product --split last3months --seed 2 --lookback 5 --J 32 --output output/product/seed:2,lookback:5
python main_depts.py --data product --split last3months --seed 2 --lookback 6 --J 32 --output output/product/seed:2,lookback:6
python main_depts.py --data product --split last3months --seed 2 --lookback 7 --J 32 --output output/product/seed:2,lookback:7
python main_depts.py --data product --split last3months --seed 3 --lookback 2 --J 32 --output output/product/seed:3,lookback:2
python main_depts.py --data product --split last3months --seed 3 --lookback 3 --J 32 --output output/product/seed:3,lookback:3
python main_depts.py --data product --split last3months --seed 3 --lookback 4 --J 32 --output output/product/seed:3,lookback:4
python main_depts.py --data product --split last3months --seed 3 --lookback 5 --J 32 --output output/product/seed:3,lookback:5
python main_depts.py --data product --split last3months --seed 3 --lookback 6 --J 32 --output output/product/seed:3,lookback:6
python main_depts.py --data product --split last3months --seed 3 --lookback 7 --J 32 --output output/product/seed:3,lookback:7
python main_depts.py --data product --split last3months --seed 4 --lookback 2 --J 32 --output output/product/seed:4,lookback:2
python main_depts.py --data product --split last3months --seed 4 --lookback 3 --J 32 --output output/product/seed:4,lookback:3
python main_depts.py --data product --split last3months --seed 4 --lookback 4 --J 32 --output output/product/seed:4,lookback:4
python main_depts.py --data product --split last3months --seed 4 --lookback 5 --J 32 --output output/product/seed:4,lookback:5
python main_depts.py --data product --split last3months --seed 4 --lookback 6 --J 32 --output output/product/seed:4,lookback:6
python main_depts.py --data product --split last3months --seed 4 --lookback 7 --J 32 --output output/product/seed:4,lookback:7
python main_depts.py --data product --split last3months --seed 5 --lookback 2 --J 32 --output output/product/seed:5,lookback:2
python main_depts.py --data product --split last3months --seed 5 --lookback 3 --J 32 --output output/product/seed:5,lookback:3
python main_depts.py --data product --split last3months --seed 5 --lookback 4 --J 32 --output output/product/seed:5,lookback:4
python main_depts.py --data product --split last3months --seed 5 --lookback 5 --J 32 --output output/product/seed:5,lookback:5
python main_depts.py --data product --split last3months --seed 5 --lookback 6 --J 32 --output output/product/seed:5,lookback:6
python main_depts.py --data product --split last3months --seed 5 --lookback 7 --J 32 --output output/product/seed:5,lookback:7



